package himedia.finalproject.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;


/*
 * [테이블 생성]
 * create table member (
 * id biging generated by default as identity,
 * name varchar(255),
 * title varchar(255),
 * contents varchar(255)
 * primary key(id)
 * );
 * 
 * [추가]
 * insert into member(name, title, contents)
 * values ('권소이', '가나다', '가나다라마바사아자차카타파하');
 * 
 */


@Entity
@Setter @Getter
@Table(name="member")
public class Member {

	@Id @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@Column(name="name")
	private String name;
	private String title;
	private String contents;
	
	public Member() {}
	
	public Member(String name, String title, String contents) {
		this.name = name;
		this.title = title;
		this.contents = contents;
	}
	
}
